// Lightweight frontend file downloader utility for TalentTrack

/**
 * Trigger an actual download of a file to the user's computer.
 */
export function downloadFile(filename, content, mimeType = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Downloads a structured CSV file given an array of headers and data rows.
 */
export function downloadCSV(filename, headers, rows) {
  const csvContent = [
    headers.map(h => `"${String(h).replace(/"/g, '""')}"`).join(','),
    ...rows.map(r => r.map(cell => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(','))
  ].join('\r\n');

  downloadFile(filename, csvContent, 'text/csv;charset=utf-8;');
}

/**
 * Downloads a professionally formatted HTML/DOC document that opens cleanly on any OS.
 */
export function downloadDocument(filename, title, bodyHtml) {
  const content = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1e293b; line-height: 1.6; }
  h1 { color: #0f172a; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; margin-bottom: 20px; }
  h2 { color: #334155; margin-top: 24px; font-size: 1.3rem; }
  p, li { font-size: 14px; color: #475569; }
  .box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 16px 0; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 14px; }
  th, td { border: 1px solid #cbd5e1; padding: 10px 12px; text-align: left; }
  th { background-color: #f1f5f9; color: #1e293b; font-weight: 600; }
  .badge { background: #dbeafe; color: #1e40af; padding: 4px 8px; border-radius: 4px; font-weight: bold; font-size: 12px; }
  .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 12px; font-size: 12px; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
  <h1>${title}</h1>
  ${bodyHtml}
  <div class="footer">Generated by TalentTrack Enterprise OS &copy; ${new Date().getFullYear()} — Official Certified Report</div>
</body>
</html>`;

  const mime = filename.endsWith('.doc') ? 'application/msword' : 'text/html;charset=utf-8';
  downloadFile(filename, content, mime);
}
